# SOURCE: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
version: '3.8'
services:
  deepdetect: 
    image: jolibrain/deepdetect_cpu
    ports:
      - "8000:8080"
    networks:
      - backend
    volumes:
      - "$HOME/.shopify-application/images:/images"

networks:
  backend:
    driver: bridge
