# SOURCE: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
version: '3.8'
services:
  api:
    build:
      context: ../../..
      dockerfile: build/api.dockerfile
    environment:
      - LOCAL_IMAGE_FOLDER=/images
      - DEEPDETECT_HOST=deepdetect:8080
      - ELASTICSEARCH_HOST=es01:9200
      - PORT=8080
    volumes:
      - "./images:/images"
    ports:
      - "8080:8080"
    restart: always
    networks:
      - backend

  # website:
  #   build:
  #     context: ../../..
  #     dockerfile: build/website.dockerfile
  #   ports:
  #     - "9090:8080"

networks:
  backend:
    driver: bridge
